module.exports = {
  apps: [
    {
      name: 'polyedge-api',
      script: 'python3',
      args: '-m uvicorn backend.api.main:app --host 0.0.0.0 --port 8100 --workers 1',
      cwd: '/home/openclaw/projects/polyedge',
      interpreter: 'none',
      env: {
        PYTHONPATH: '/home/openclaw/projects/polyedge',
      },
      watch: false,
      restart_delay: 5000,
      max_restarts: 50,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-api-error.log',
      out_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-api-out.log',
    },
    {
      name: 'polyedge-frontend',
      script: 'sh',
      args: '-c "[ -d dist ] || npm run build && npx vite preview --host 0.0.0.0 --port 5174"',
      cwd: '/home/openclaw/projects/polyedge/frontend',
      interpreter: 'none',
      watch: false,
      restart_delay: 5000,
      max_restarts: 50,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-frontend-error.log',
      out_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-frontend-out.log',
    },
    {
      name: 'polyedge-bot',
      script: 'python3',
      args: '-m backend.core.orchestrator',
      cwd: '/home/openclaw/projects/polyedge',
      interpreter: 'none',
      env: {
        PYTHONPATH: '/home/openclaw/projects/polyedge',
      },
      watch: false,
      restart_delay: 5000,
      max_restarts: 50,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-bot-error.log',
      out_file: '/home/openclaw/projects/polyedge/.omc/logs/polyedge-bot-out.log',
    },
  ],
}
