import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [{type: 'autogenerated', dirName: 'dashboard'}],
    },
    {
      type: 'category',
      label: 'Admin Panel',
      items: [{type: 'autogenerated', dirName: 'admin'}],
    },
    {
      type: 'category',
      label: 'Strategies',
      items: [{type: 'autogenerated', dirName: 'strategies'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
  ],
};

export default sidebars;
